sudo: required

language: java

services:
  - docker

jdk:
  - oraclejdk11

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - bash <(curl -s https://codecov.io/bash)

  - export REPO=mwvdev/aptpeeker
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export JAR_FILE=$(ls ./build/libs/aptpeeker-*.jar)

  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

  - docker build --build-arg JAR_FILE=$JAR_FILE -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG

  - docker push $REPO

notifications:
  slack:
    secure: NA5aW29bjA7uwZmobSL3m/TyKWyowTlRcQUtuha5YEstrRw22bz4qCPKZVibFsugHYToVxCi5Pg8jq8/Bv0NoV4jCUUJPLtFHJnzqorBaTgCqu0wBLPRDX/AEj5jumK0VfXfbolakW4dNFWMG0N/+9hnyuA3WOAbJ0XD+nhVCKJ5hot296x2Eu4AeQIv/9/bxEyHkqlUK1WS/Up0bETdu25TX15tLU+1NCz2U994767PYVeXmcFgW0eql0sFfNVkndDhhFTbVFXTUQh+aBcFQxcaSK3FL0U9iTN+DJRJ0zbAPnITkJGuTK8SIoj9USy8dOk5WEb0TDWxcZdyd3LAeJuT1/AQ0oCSAnqdbuGndmVsV0z71LsD8ZB6bizGl4Uq07pZIiwIIPAOt9VsjanxsvdQWEWgut3pQ5cP7HFIFEkkG4W+6fo0oxGmueQLliMJiDs48hZ+e8xtCFNRf8zEIQZvo/JK2NZN+88pH1m5sqOGJYmUtnogAxCv1ZQQ7GInl0+SOTMXXBkBvDh5yst2Ou8UhwkV2gRZ16mrMk+CBmLWGS2GsSb/roezUXpQ7t7zuihewHn6uLfbygBpQ94LQYgC1woPRrmFIM5z71s7CjC3K78iUoWDBMqIPaCeuyw21r9D+WFds90nVA2q3czWJ/iBH8A/Rj7i9xoluMgcY4Q=
